<?php
$title = "Add new Album";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('album',array('action'=>'add')));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

//echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('title'));
//echo $this->formRow($form->get('artist'));
//echo $this->formSubmit($form->get('submit'));
//echo $this->form()->closeTag($form);

// Simple Way to render form
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);